controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 10.0
    progress_checker_plugin: "nav2_controller/SimpleProgressChecker"
    goal_checker_plugin: "nav2_controller/SimpleGoalChecker"
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core/DWBLocalPlanner"
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]

planner_server:
  ros__parameters:
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

behavior_server:
  ros__parameters:
    use_sim_time: True
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"

# --- MUDANÇAS IMPORTANTES AQUI ---
local_costmap:
  ros__parameters:
    use_sim_time: True
    update_frequency: 5.0
    publish_frequency: 2.0
    global_frame: odom
    robot_base_frame: base_footprint
    rolling_window: true
    width: 5
    height: 5
    resolution: 0.05
    plugins: ["inflation_layer"] # Apenas a camada de inflação
    inflation_layer:
      plugin: "nav2_costmap_2d/InflationLayer"
      cost_scaling_factor: 3.0
      inflation_radius: 0.55
    always_send_full_costmap: True

global_costmap:
  ros__parameters:
    use_sim_time: True
    update_frequency: 1.0
    publish_frequency: 1.0
    global_frame: map
    robot_base_frame: base_footprint
    rolling_window: false
    plugins: ["static_layer", "inflation_layer"] # Apenas estática e inflação
    static_layer:
      plugin: "nav2_costmap_2d/StaticLayer"
      map_subscribe_transient_local: True
    inflation_layer:
      plugin: "nav2_costmap_2d/InflationLayer"
      cost_scaling_factor: 3.0
      inflation_radius: 0.55
    always_send_full_costmap: True

# O resto dos parâmetros
amcl:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    odom_frame_id: "odom"
    robot_model_type: "nav2_amcl::DifferentialMotionModel"

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "map.yaml"